name: spectacle

channels:
    - astropy

dependencies:
    - python>=3.5
    - astropy
    - Cython
    - matplotlib
    - numpy
    - pyyaml
    - pathos
    - pip:
        - sphinx-astropy
        - sphinx-rtd-theme
